### PR TITLE
Use cl-generic macros

### PR DESCRIPTION
**Pull request by marsam**
defmethod/defgeneric are deprecated as of Emacs 25.1

### CODE REVIEW

**Comment by skeeto** [comment]
Thanks for taking the time to do this. However, Emacs 25.1 was only
released 6 months ago. I'm not ready to make it a hard requirement for
EmacSQL. That day will eventually come, at which point I will merge this
PR, but for now I will continue supporting back to Emacs 24.3. That was
a major release and supporting further back than 24.3 is difficult,
which is what makes that version special.

**Comment by marsam** [comment]
I understand. There is [`cl-generic` available in elpa](https://elpa.gnu.org/packages/cl-generic.html) for Emacs<25. Can you consider add it as a dependency?

**Comment by tarsius** [comment]
> Can you consider add it as a dependency?

I've done that in #32.

**Comment by skeeto** [comment]
Merged via #32. Thanks for initiating this, @marsam!

**Pull request closed without merging**
