### PR TITLE
Expand identifier vectors when passed as parameters (#7).

### PR DESCRIPTION
**Pull request by tarsius**
Following up on #7:

This just implements what I originally asked for, support for `[:select $i1 ...] (vector 'foo 'bar)`. (With the exception, that it uses `$i` instead of `$v`, taking your explanations into account.

> Also, if you really wanted it to be complete, [...]

This does not support expressions inside the identifiers. Doing that would mean that there would be a second "prepare-time" during "format-time". And that would require that parameters would be collected again, but currently there is no support for that, which probably is a good thing. So I use `mapconcat` instead of `emacsql--*combine` and `emacsql--*idents`.

And I don't really see how `[:select $i1 ...] [(* a 2)]` would be better than just `[:select [(* a 2)] ...]`. If there are to be expressions here, then one would likely hard-code them anway or one would have to resort to manually constructing the vector and the contained expressions anyway.

Maybe there's a use-case for preparing not only SQL but also some of the vectors among ARGS, but I don't see it right now. So for now I am keeping it simple.

### CODE REVIEW

**Comment by skeeto** [comment]
> This does not support expressions inside the identifiers.

I'd say because of this it's kind of a hack. But since dynamically selecting columns is itself a dirty hack, and this change doesn't hurt anything else, that's perfectly fine.

Thanks!

**Comment by tarsius** [comment]
I'm using emacsql more and more, so maybe some other time :-)

**Comment by tarsius** [comment]
Would this be an acceptable extension?

```diff
diff --git a/emacsql-compiler.el b/emacsql-compiler.el
index 3267d18..2885152 100644
--- a/emacsql-compiler.el
+++ b/emacsql-compiler.el
@@ -62,8 +62,11 @@ (defun emacsql-escape-identifier (identifier)
             (not (or (symbolp identifier)
                      (vectorp identifier))))
     (emacsql-error "Invalid identifier: %S" identifier))
-  (if (vectorp identifier)
-      (mapconcat #'emacsql-escape-identifier identifier ", ")
+  (cond
+   ((vectorp identifier)
+    (mapconcat #'emacsql-escape-identifier identifier ", "))
+   ((eq identifier '*) "*")
+   (t
     (let ((name (symbol-name identifier)))
       (if (string-match-p ":" name)
           (mapconcat #'emacsql-escape-identifier
@@ -74,7 +77,7 @@ (defun emacsql-escape-identifier (identifier)
                   (string-match-p "^[0-9$]" print)
                   (emacsql-reserved-p print))
               (emacsql-quote-identifier print)
-            print))))))
+            print)))))))
 
 (defun emacsql-escape-scalar (value)
   "Escape VALUE for sending to SQLite."
```

**Comment by skeeto** [comment]
It's so acceptable that I went ahead and committed it myself, with you 
as the author. This change makes it slightly more convoluted and 
surprising to refer to a literal "*" column — the easy workaround is to 
use an uninterned symbol (e.g. #:*). But since that would make for a 
stupid column name, this extension is fine. Also, as I've said before, 
dynamic identifier substitution is a big, nasty hack anyway, so I don't 
mind it being imprecise.

Thanks, Jonas!

**Comment by tarsius** [comment]
Great!

**Comment by skeeto** [comment]
Is this the change you said you wanted to have tagged?

**Comment by tarsius** [comment]
Yes, but if you have already pushed the other tag, then it really isn't necessary that you create another release just for this.

**Pull request merged**
